apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: userdata-net-pol
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: backend-userdata
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: backend-apigate
    ports:
    - protocol: TCP
      port: 8081   # assuming pod port for user-data service

  egress:
  - to:
    - podSelector:
        matchLabels:
          app: postgres
    ports:
    - protocol: TCP
      port: 5432
