apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment-suggest
  labels:
    app: backend-suggest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-suggest
  template:
    metadata:
      labels:
        app: backend-suggest
    spec:
      containers:
      - name: backend
        image: akshat1414/suggest:v2
        ports:
        - containerPort: 8083
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-secrets
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-secrets
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_REGION
          valueFrom:
            secretKeyRef:
              name: aws-secrets
              key: AWS_REGION
