apiVersion: v1
kind: Secret
metadata:
  name: aws-secrets
type: Opaque
data:
  AWS_ACCESS_KEY_ID: QUtJQVQ0TDdORUxBRzRZRU4zWko=
  AWS_SECRET_ACCESS_KEY: MlBDK3ZPZ1RyQzJFdzVZM243NVNUTytIQVZHUVRCTHpyZVVtU0hzbA==
  AWS_REGION: dXMtZWFzdC0x
